name: jukevault_android
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
homepage:

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  jukevault_platform_interface: 
    git:
      url: https://github.com/IGraysonI/jukevault
      path: packages/jukevault_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: jukevault
    platforms:
      android:
        package: com.example.jukevault_android
        pluginClass: JukevaultAndroidPlugin
