name: jukevault_android
description: Android implementation of the jukevault plugin.
version: 0.0.1
homepage: https://github.com/IGraysonI/jukevault/packages/jukevault_android
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  jukevault_platform_interface:
    git:
      url: https://github.com/IGraysonI/jukevault
      path: packages/jukevault_platform_interface
      ref: android_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    implements: jukevault
    platforms:
      android:
        package: com.IGraysonI.jukevault_android
        pluginClass: JukevaultAndroidPlugin
        # dartPluginClass: JukevaultPluginAndroid
      