name: jukevault_android
description: Android implementation of the jukevault plugin.
version: 0.0.2
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  jukevault_platform_interface:
    path: ../jukevault_platform_interface
    # git:
    #   url: https://github.com/igraysoni/jukevault
    #   path: packages/jukevault_platform_interface
    #   ref: main

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    implements: jukevault
    platforms:
      android:
        package: com.igraysonl.jukevault
        pluginClass: JukevaultPlugin
