name: jukevault_platform_interface
description: A common platform interface for the [jukevault] plugin.
version: 0.0.1
publish_to: 'none'

environment:
  #TODO: Up SDK and Flutter versions
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  plugin_platform_interface: ^2.1.3

  # TODO: Discontinued, find a new package
  id3: ^1.0.2
  path: ^1.8.2
  path_provider: ^2.0.12

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
