name: jukevault_platform_interface
description: A common platform interface for the [jukevault] plugin.
version: 0.0.3
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  plugin_platform_interface: ^2.1.8

  # TODO: Discontinued, find a new package
  id3: ^1.0.2
  path: ^1.9.0
  path_provider: ^2.1.4

  # Flutter
  flutter:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
