name: jukevault_platform_interface
description: "A new Flutter plugin project."
version: 0.0.1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  plugin_platform_interface: ^2.1.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
