name: jukevault_android_example
description: "Demonstrates how to use the jukevault_android plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  jukevault_android:
    path: ../

  cupertino_icons: ^1.0.6
  l: ^4.0.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
