name: jukevault
description: Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage.
version: 0.0.2
publish_to: 'none' 

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  jukevault_platform_interface:
    path: ../jukevault_platform_interface
  jukevault_android:
    path: ../jukevault_android

  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Design
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: jukevault_android
