name: jukevault
description: Plugin for reading and writing local music files 
version: 0.0.1
homepage: https://github.com/igraysoni/jukevault
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

  jukevault_platform_interface:
    git:
      url: https://github.com/igraysoni/jukevault
      path: packages/jukevault_platform_interface
      ref: android_base
  jukevault_android:
    git:
      url:  https://github.com/igraysoni/jukevault
      path: packages/jukevault_android
      ref: android_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: jukevault_android
        package: com.igraysoni.jukevault
        pluginClass: JukevaultPlugin
      # ios:
      #   pluginClass: JukevaultPlugin
      # linux:
      #   pluginClass: JukevaultPlugin
      # macos:
      #   pluginClass: JukevaultPlugin
      # windows:
      #   pluginClass: JukevaultPluginCApi
