name: jukevault
description: Flutter Plugin used to query audios/songs infos [title, artist, album, etc..] from device storage.
version: 0.0.1
publish_to: 'none' 

environment:
  # TODO: Update
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  jukevault_platform_interface:
    path: ../jukevault_platform_interface
  jukevault_android:
    path: ../jukevault_android

  # Flutter
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  # Flutter
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  # Material Design
  uses-material-design: true
  plugin:
    platforms:
      android:
        default_package: jukevault_android
